# Basic WINDOWS 10 Alacritty configuration file
# https://alacritty.org/config-alacritty.html
# By Github:@dcrobin1973

general.working_directory = "c:\\"
general.live_config_reload = true

[terminal.shell]
program = "pwsh.exe"
args = ["-NoLogo", "-NoProfile"]

[colors]
[colors.primary]
foreground = "#adadad"
background = "#171a21"
dim_foreground = "#292e37"

[window]
dimensions = { columns = 135, lines = 35 }
position = { x = 550, y = 200 }
padding = { x = 1, y = 1 }
opacity = 0.9
decorations_theme_variant = "none"
startup_mode = "Windowed"

[scrolling]
history = 1000
multiplier = 5

[font]
normal = { family = "Lucida Console", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
offset = { x = 1, y = 0 }
size = 9.0
builtin_box_drawing = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[keyboard]
bindings = [
{ key = "N", mods = "Control", action = "CreateNewWindow" },
{ key = "H", mods = "Control", action = "Hide" },
{ key = "C", mods = "Control", action = "Copy" },
{ key = "V", mods = "Control", action = "Paste" },
{ key = "Q", mods = "Control", action = "Quit" },
#{ key = "X", mods = "Control", chars = "cls" },
]

[mouse]
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
{ mouse = "Middle", mods = "Control", action = "Copy" },
]
